### PR TITLE
Add constexpr requirement for macOS

### PR DESCRIPTION
**Pull request by jedahan**
I needed to do this to get working on macOS

### CODE REVIEW

**Comment by gmrt** [comment]
`target_compile_features` requires CMake 3.1.0, so you should change `cmake_minimum_required`.

Anyway, in case you don't know, there's a python script that can verify the updates: https://github.com/LineageOS/update_verifier

**Comment by jedahan** [comment]
@gmrt will do!

Unfortunately that update_verifier has the key in a different format - do you have a copy of the key in this repository that is compatible with that format?

**Comment by gmrt** [comment]
[The public key is in the repo](https://github.com/LineageOS/update_verifier/blob/master/lineageos_pubkey).

**Comment by jedahan** [comment]
I was confused and thought this project was related to https://lineage.microg.org/, my bad

**Comment by firetray-updates** [comment]
In that case, grab the certificate that is in `/system/etc/security/otacerts.zip` and run
`openssl x509 -pubkey -noout -in releasekey.x509.pem | openssl rsa -pubin -RSAPublicKey_out`

**Comment by gmrt** [comment]
In that case, grab the certificate that is in `/system/etc/security/otacerts.zip` and run
`openssl x509 -pubkey -noout -in releasekey.x509.pem | openssl rsa -pubin -RSAPublicKey_out`

**Pull request closed without merging**
